// Code generated by Icestudio 0.2.2-dev
// Thu, 17 Nov 2016 19:40:00 GMT

`default_nettype none

module main (input vd9b5c7,
             input va55d5a,
             input v006143,
             output vfe8161);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 assign w0 = vd9b5c7;
 assign w2 = va55d5a;
 assign w4 = v006143;
 assign w9 = vd9b5c7;
 assign w10 = va55d5a;
 assign w11 = v006143;
 assign vfe8161 = w13;
 assign w9 = w0;
 assign w10 = w2;
 assign w11 = w4;
 main_logic_gate_and vbcc84a (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w3)
 );
 main_logic_gate_and v3cc07d (
  .v0e28cb(w3),
  .v3ca442(w4),
  .vcbab45(w5)
 );
 main_logic_gate_or veb55c4 (
  .v0e28cb(w5),
  .v3ca442(w6),
  .vcbab45(w12)
 );
 main_logic_gate_or vaf19bb (
  .v3ca442(w10),
  .v0e28cb(w12),
  .vcbab45(w13)
 );
 main_logic_gate_and v8688cf (
  .vcbab45(w6),
  .v0e28cb(w7),
  .v3ca442(w8)
 );
 main_logic_gate_not v62acdc (
  .vcbab45(w1),
  .v0e28cb(w2)
 );
 main_logic_gate_not v9ecb77 (
  .vcbab45(w7),
  .v0e28cb(w9)
 );
 main_logic_gate_not vfd1241 (
  .vcbab45(w8),
  .v0e28cb(w11)
 );
endmodule

module main_logic_gate_and (input v0e28cb,
                            input v3ca442,
                            output vcbab45);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 main_logic_gate_and_basic_code_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

module main_logic_gate_and_basic_code_vf4938a (input a,
                                               input b,
                                               output c);
 // AND logic gate
 
 assign c = a & b;
endmodule

module main_logic_gate_or (input v0e28cb,
                           input v3ca442,
                           output vcbab45);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 main_logic_gate_or_basic_code_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

module main_logic_gate_or_basic_code_vf4938a (input a,
                                              input b,
                                              output c);
 // OR logic gate
 
 assign c = a | b;
endmodule

module main_logic_gate_not (input v0e28cb,
                            output vcbab45);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 main_logic_gate_not_basic_code_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

module main_logic_gate_not_basic_code_vd54ca1 (input a,
                                               output c);
 // NOT logic gate
 
 assign c = ~ a;
endmodule

