// Code generated by Icestudio 0.2.2-dev
// Thu, 17 Nov 2016 19:40:09 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns

module main_tb ();
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // Input/Output
 reg input_A;
 reg input_B;
 reg input_C;
 wire output_Out_1;
 
 // Module instance
 main MAIN (
  .vd9b5c7(input_A),
  .va55d5a(input_B),
  .v006143(input_C),
  .vfe8161(output_Out_1)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. input_value = 1;
  // e.g. #2 input_value = 0;
  input_A = 0;
  input_B = 0;
  input_C = 0;
  
  
  // JJVITON testing process
  
  //input_in_x =0;
  input_A = 1'b0;
  input_B = 1'b0;
  input_C = 1'b0;
  
  #50  // espero un poco para empezar.
  
  input_A = 1'b0;
  input_B = 1'b0;
  input_C = 1'b1;
  #20
  input_A = 1'b0;
  input_B = 1'b1;
  input_C = 1'b0;
  #20 
  input_A = 1'b0;
  input_B = 1'b1;
  input_C = 1'b1;
  #20  
  input_A = 1'b1;
  input_B = 1'b0;
  input_C = 1'b0;
  #20
  input_A = 1'b1;
  input_B = 1'b0;
  input_C = 1'b1;
  #20  
  input_A = 1'b1;
  input_B = 1'b1;
  input_C = 1'b0;
  #20 
  input_A = 1'b1;
  input_B = 1'b1;
  input_C = 1'b1;
  #20    
  
  
  
// JJVITON testing process  (fin) 
  
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule

