// Code generated by Icestudio 0.2.2-dev
// Wed, 09 Nov 2016 09:57:31 GMT

`default_nettype none

module main (input v134b2d,
             input vf0ea54,
             input vf04341,
             output v70fc16,
             output vaff669);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 assign w1 = vf04341;
 assign v70fc16 = w2;
 assign w3 = v134b2d;
 assign w4 = vf0ea54;
 assign w5 = v134b2d;
 assign vaff669 = w6;
 assign w8 = vf04341;
 assign w9 = vf0ea54;
 assign w5 = w3;
 assign w8 = w1;
 assign w9 = w4;
 main_logic_gate_or ve544d9 (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w2)
 );
 main_logic_gate_or v8e013b (
  .vcbab45(w0),
  .v0e28cb(w3),
  .v3ca442(w4)
 );
 main_logic_gate_or vbc0589 (
  .v0e28cb(w5),
  .vcbab45(w6),
  .v3ca442(w7)
 );
 main_logic_gate_or vee13da (
  .vcbab45(w7),
  .v3ca442(w8),
  .v0e28cb(w9)
 );
endmodule

module main_logic_gate_or (input v0e28cb,
                           input v3ca442,
                           output vcbab45);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 main_logic_gate_or_basic_code_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

module main_logic_gate_or_basic_code_vf4938a (input a,
                                              input b,
                                              output c);
 // OR logic gate
 
 assign c = a | b;
endmodule

