// Code generated by Icestudio 0.2.2-dev
// Fri, 11 Nov 2016 08:26:40 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns

module main_tb ();
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // Input/Output
 reg input_a;
 reg input_b;
 wire output_o;
 wire output_o2;
 
 // Module instance
 main MAIN (
  .v134b2d(input_a),
  .vf0ea54(input_b),
  .v70fc16(output_o),
  .vaff669(output_o2)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. input_value = 1;
  // e.g. #2 input_value = 0;

  
  
 
// JJVITON testing process
  
  //input_in_x =1;
  input_a = 1'b1;
  input_b = 1'b1;
  
  #50  // espero un poco para empezar.
  
  
  input_a = 1'b0;  //0
  input_b = 1'b1;
  #20
  input_a = 1'b0;  
  input_b = 1'b0;
  #20
  input_a = 1'b0;  //0
  input_b = 1'b0;
  #20
  input_a = 1'b0;  //0
  input_b = 1'b1;
  #20
  input_a = 1'b1;  //1
  input_b = 1'b0;
  #20
  
// JJVITON testing process  (fin) 
  
  
  
  
  
  
  
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule

