// Code generated by Icestudio 0.2.2-dev
// Sat, 05 Nov 2016 23:47:24 GMT

`default_nettype none

module main (input v6d4cdf,
             output vabc7eb);
 wire w0;
 wire w1;
 assign w0 = v6d4cdf;
 assign vabc7eb = w1;
 main_logic_gate_not vcfedf9 (
  .v0e28cb(w0),
  .vcbab45(w1)
 );
endmodule

module main_logic_gate_not (input v0e28cb,
                            output vcbab45);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 main_logic_gate_not_basic_code_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

module main_logic_gate_not_basic_code_vd54ca1 (input a,
                                               output c);
 // NOT logic gate
 
 assign c = ~ a;
endmodule

