// Code generated by Icestudio 0.2.2-dev
// Wed, 02 Nov 2016 17:33:01 GMT
// JJVITON 

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns

module main_tb ();
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // Input/Output
 reg input_A;
 reg input_B;
 wire output_o;
 
 // Module instance
 main MAIN (
  .v963cc9(input_A),
  .v645ecc(input_B),
  .vd1c097(output_o)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. input_value = 1;
  // e.g. #2 input_value = 0;
  input_A = 0;
  input_B = 0;
  
    // JJVITON testing process
  
    //input_in_a =0;
  input_A = 1'b0;
  input_B =0;
  
  #50  // espero un poco para empezar.
  input_B =1;
  
  input_A = 1'b0;  //1
  #20
  input_A = 1'b1;  //0
  #20
  
//

  input_B =0;
 
  input_A = 1'b1;  //1
  #20
  input_A = 1'b0;   //0
  #20
  
  // JJVITON testing process  (fin) 
  
  
  
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule

