// Code generated by Icestudio 0.2.2-dev
// Wed, 02 Nov 2016 17:32:49 GMT

`default_nettype none

module main (input v963cc9,
             input v645ecc,
             output vd1c097);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v645ecc;
 assign w1 = v963cc9;
 assign vd1c097 = w2;
 main_logic_gate_or v9285f8 (
  .v3ca442(w0),
  .v0e28cb(w1),
  .vcbab45(w2)
 );
endmodule

module main_logic_gate_or (input v0e28cb,
                           input v3ca442,
                           output vcbab45);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 main_logic_gate_or_basic_code_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

module main_logic_gate_or_basic_code_vf4938a (input a,
                                              input b,
                                              output c);
 // OR logic gate
 
 assign c = a | b;
endmodule

